Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -47,7 +47,7 @@ jobs:
           publish_dir: build
           force_orphan: true
           allow_empty_commit: true
-          cname: mypage.hbrown-test.com
+          cname: mypage2.hbrown-test.com
 
       - name: Enable Enforce HTTPS
         env:
@@ -56,9 +56,28 @@ jobs:
         run: |
           OWNER=$(echo $REPO | awk -F'/' '{print $1}')
           REPO_NAME=$(echo $REPO | awk -F'/' '{print $2}')
-          curl -L \
-            -X PUT \
-            -H "Authorization: token $HTTPS_TOKEN" \
-            -H "Accept: application/vnd.github+json" \
-            https://api.github.com/repos/hebrown/docusaurus-test-changes/pages \
-            -d '{"https_enforced": true}'
+          MAX_RETRIES=30
+          RETRY_INTERVAL=30
+          for ((i=1; i<=MAX_RETRIES; i++)); do
+            echo "Attempt $i to enforce HTTPS"
+            RESPONSE=$(curl -L -s -o response.json -w "%{http_code}" \
+              -X PUT \
+              -H "Authorization: token $HTTPS_TOKEN" \
+              -H "Accept: application/vnd.github+json" \
+              https://api.github.com/repos/$OWNER/$REPO_NAME/pages \
+              -d '{"https_enforced": true}')
+            HTTP_STATUS=$(echo "$RESPONSE" | tail -n1)
+            if [[ "$HTTP_STATUS" == "204" ]]; then
+              echo "HTTPS enforcement successful"
+              cat response.json
+              break
+            else
+              echo "HTTPS enforcement failed with status $HTTP_STATUS. Retrying in $RETRY_INTERVAL seconds..."
+              cat response.json
+              sleep $RETRY_INTERVAL
+            fi
+          done
+          if [[ "$HTTP_STATUS" != "204" ]]; then
+            echo "Failed to enforce HTTPS after $MAX_RETRIES attempts."
+            exit 1
+          fi
